## Tasca S12.01. APIs REST

Descripció
Aplicaràs el que has après sobre APIs REST, mètodes HTTP i codis d'estat, utilitzant APIs públiques per consultar dades, filtrar-les i finalment desar-les en un DataFrame de pandas.

# Recursos:
**Nivell 1:**
{JSON} Placeholder
**Nivell 2:**
Try Public APIs for free
**Nivell 3:**
Open Data BCN

**Nivell 1**

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.
*1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:*

Llista de publicacions (/posts)
Llista d’usuaris (/users)
Llista de tasques (/todos)

In [3]:
import requests

url = "https://jsonplaceholder.typicode.com/"

#Llista de publicacions (/posts)
posts = requests.get(f"{url}/posts")
print(posts.json())

#Llista d’usuaris (/users)
users = requests.get(f"{url}/users")
print(users.json())

#Llista de tasques (/todos)
todos = requests.get(f"{url}/todos")
print(todos.json())

[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'}, {'userId': 1, 'id': 5, 'title': 'nesciunt quas odio', 'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'}, {'userId': 1, 'id': 6, 'title': 'dolorem eum magni eos aperiam quia', 'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'}, {'userId': 1, 'id': 7, 'title': 'magnam facilis autem', 'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'}, {'userId': 1, 'id': 8, 'title': 'dolorem dolore est ipsam', 'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'}, {'userId': 1, 'id': 9, 'title': 'nesciunt iure omnis dolorem tempora et accusantium', 'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'}, {'userId': 1, 'id': 10, 'title': 'optio molestias id quia eum', 'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'}, {'userId': 2, 'id': 11, 'title': 'et ea vero quia laudantium autem', 'body': 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi'}, {'userId': 2, 'id': 12, 'title': 'in quibusdam tempore odit est dolorem', 'body': 'itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio'}, {'userId': 2, 'id': 13, 'title': 'dolorum ut in voluptas mollitia et saepe quo animi', 'body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam'}, {'userId': 2, 'id': 14, 'title': 'voluptatem eligendi optio', 'body': 'fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum'}, {'userId': 2, 'id': 15, 'title': 'eveniet quod temporibus', 'body': 'reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae'}, {'userId': 2, 'id': 16, 'title': 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio', 'body': 'suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta'}, {'userId': 2, 'id': 17, 'title': 'fugit voluptas sed molestias voluptatem provident', 'body': 'eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo'}, {'userId': 2, 'id': 18, 'title': 'voluptate et itaque vero tempora molestiae', 'body': 'eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam'}, {'userId': 2, 'id': 19, 'title': 'adipisci placeat illum aut reiciendis qui', 'body': 'illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas'}, {'userId': 2, 'id': 20, 'title': 'doloribus ad provident suscipit at', 'body': 'qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo'}, {'userId': 3, 'id': 21, 'title': 'asperiores ea ipsam voluptatibus modi minima quia sint', 'body': 'repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt'}, {'userId': 3, 'id': 22, 'title': 'dolor sint quo a velit explicabo quia nam', 'body': 'eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse'}, {'userId': 3, 'id': 23, 'title': 'maxime id vitae nihil numquam', 'body': 'veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis'}, {'userId': 3, 'id': 24, 'title': 'autem hic labore sunt dolores incidunt', 'body': 'enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt'}, {'userId': 3, 'id': 25, 'title': 'rem alias distinctio quo quis', 'body': 'ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio'}, {'userId': 3, 'id': 26, 'title': 'est et quae odit qui non', 'body': 'similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero'}, {'userId': 3, 'id': 27, 'title': 'quasi id et eos tenetur aut quo autem', 'body': 'eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur'}, {'userId': 3, 'id': 28, 'title': 'delectus ullam et corporis nulla voluptas sequi', 'body': 'non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum'}, {'userId': 3, 'id': 29, 'title': 'iusto eius quod necessitatibus culpa ea', 'body': 'odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores'}, {'userId': 3, 'id': 30, 'title': 'a quo magni similique perferendis', 'body': 'alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia'}, {'userId': 4, 'id': 31, 'title': 'ullam ut quidem id aut vel consequuntur', 'body': 'debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae'}, {'userId': 4, 'id': 32, 'title': 'doloremque illum aliquid sunt', 'body': 'deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime'}, {'userId': 4, 'id': 33, 'title': 'qui explicabo molestiae dolorem', 'body': 'rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod'}, {'userId': 4, 'id': 34, 'title': 'magnam ut rerum iure', 'body': 'ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis'}, {'userId': 4, 'id': 35, 'title': 'id nihil consequatur molestias animi provident', 'body': 'nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit'}, {'userId': 4, 'id': 36, 'title': 'fuga nam accusamus voluptas reiciendis itaque', 'body': 'ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore'}, {'userId': 4, 'id': 37, 'title': 'provident vel ut sit ratione est', 'body': 'debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui'}, {'userId': 4, 'id': 38, 'title': 'explicabo et eos deleniti nostrum ab id repellendus', 'body': 'animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure'}, {'userId': 4, 'id': 39, 'title': 'eos dolorem iste accusantium est eaque quam', 'body': 'corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex'}, {'userId': 4, 'id': 40, 'title': 'enim quo cumque', 'body': 'ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam'}, {'userId': 5, 'id': 41, 'title': 'non est facere', 'body': 'molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe'}, {'userId': 5, 'id': 42, 'title': 'commodi ullam sint et excepturi error explicabo praesentium voluptas', 'body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut'}, {'userId': 5, 'id': 43, 'title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis', 'body': 'similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis'}, {'userId': 5, 'id': 44, 'title': 'optio dolor molestias sit', 'body': 'temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae'}, {'userId': 5, 'id': 45, 'title': 'ut numquam possimus omnis eius suscipit laudantium iure', 'body': 'est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem'}, {'userId': 5, 'id': 46, 'title': 'aut quo modi neque nostrum ducimus', 'body': 'voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid'}, {'userId': 5, 'id': 47, 'title': 'quibusdam cumque rem aut deserunt', 'body': 'voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate'}, {'userId': 5, 'id': 48, 'title': 'ut voluptatem illum ea doloribus itaque eos', 'body': 'voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit'}, {'userId': 5, 'id': 49, 'title': 'laborum non sunt aut ut assumenda perspiciatis voluptas', 'body': 'inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut'}, {'userId': 5, 'id': 50, 'title': 'repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem', 'body': 'error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur'}, {'userId': 6, 'id': 51, 'title': 'soluta aliquam aperiam consequatur illo quis voluptas', 'body': 'sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem'}, {'userId': 6, 'id': 52, 'title': 'qui enim et consequuntur quia animi quis voluptate quibusdam', 'body': 'iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum'}, {'userId': 6, 'id': 53, 'title': 'ut quo aut ducimus alias', 'body': 'minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique'}, {'userId': 6, 'id': 54, 'title': 'sit asperiores ipsam eveniet odio non quia', 'body': 'totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia'}, {'userId': 6, 'id': 55, 'title': 'sit vel voluptatem et non libero', 'body': 'debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit'}, {'userId': 6, 'id': 56, 'title': 'qui et at rerum necessitatibus', 'body': 'aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi'}, {'userId': 6, 'id': 57, 'title': 'sed ab est est', 'body': 'at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est'}, {'userId': 6, 'id': 58, 'title': 'voluptatum itaque dolores nisi et quasi', 'body': 'veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam'}, {'userId': 6, 'id': 59, 'title': 'qui commodi dolor at maiores et quis id accusantium', 'body': 'perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt'}, {'userId': 6, 'id': 60, 'title': 'consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere', 'body': 'asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis'}, {'userId': 7, 'id': 61, 'title': 'voluptatem doloribus consectetur est ut ducimus', 'body': 'ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit'}, {'userId': 7, 'id': 62, 'title': 'beatae enim quia vel', 'body': 'enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio'}, {'userId': 7, 'id': 63, 'title': 'voluptas blanditiis repellendus animi ducimus error sapiente et suscipit', 'body': 'enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta'}, {'userId': 7, 'id': 64, 'title': 'et fugit quas eum in in aperiam quod', 'body': 'id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui'}, {'userId': 7, 'id': 65, 'title': 'consequatur id enim sunt et et', 'body': 'voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur'}, {'userId': 7, 'id': 66, 'title': 'repudiandae ea animi iusto', 'body': 'officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe'}, {'userId': 7, 'id': 67, 'title': 'aliquid eos sed fuga est maxime repellendus', 'body': 'reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae'}, {'userId': 7, 'id': 68, 'title': 'odio quis facere architecto reiciendis optio', 'body': 'magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit'}, {'userId': 7, 'id': 69, 'title': 'fugiat quod pariatur odit minima', 'body': 'officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a'}, {'userId': 7, 'id': 70, 'title': 'voluptatem laborum magni', 'body': 'sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore'}, {'userId': 8, 'id': 71, 'title': 'et iusto veniam et illum aut fuga', 'body': 'occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis'}, {'userId': 8, 'id': 72, 'title': 'sint hic doloribus consequatur eos non id', 'body': 'quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit'}, {'userId': 8, 'id': 73, 'title': 'consequuntur deleniti eos quia temporibus ab aliquid at', 'body': 'voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut'}, {'userId': 8, 'id': 74, 'title': 'enim unde ratione doloribus quas enim ut sit sapiente', 'body': 'odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora'}, {'userId': 8, 'id': 75, 'title': 'dignissimos eum dolor ut enim et delectus in', 'body': 'commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem'}, {'userId': 8, 'id': 76, 'title': 'doloremque officiis ad et non perferendis', 'body': 'ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio'}, {'userId': 8, 'id': 77, 'title': 'necessitatibus quasi exercitationem odio', 'body': 'modi ut in nulla repudiandae dolorum nostrum eos\naut consequatur omnis\nut incidunt est omnis iste et quam\nvoluptates sapiente aliquam asperiores nobis amet corrupti repudiandae provident'}, {'userId': 8, 'id': 78, 'title': 'quam voluptatibus rerum veritatis', 'body': 'nobis facilis odit tempore cupiditate quia\nassumenda doloribus rerum qui ea\nillum et qui totam\naut veniam repellendus'}, {'userId': 8, 'id': 79, 'title': 'pariatur consequatur quia magnam autem omnis non amet', 'body': 'libero accusantium et et facere incidunt sit dolorem\nnon excep

*2. Mostra per pantalla:*

La quantitat total de cada recurs.
El codi d'estat de cada petició.

In [7]:
#La quantitat total de cada recurs.
print("Total posts:", len(posts.json()))
print("Total users:", len(users.json()))
print("Total todos:", len(todos.json()))

#El codi d'estat de cada petició.
print("Status_code posts:", posts.status_code)
print("Status_code users:", users.status_code)
print("Status_code todos:", todos.status_code)

Total posts: 100
Total users: 10
Total todos: 200
Status_code posts: 200
Status_code users: 200
Status_code todos: 200

*3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.*

In [8]:
error_404 = requests.get(f"{url}/posts/119")
print("Status_code error:", error_404.status_code)

Status_code error: 404

*4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.*

Mostra la resposta JSON.
Mostra el codi d'estat.

In [10]:
publicacion_ficticia = {"title": "Título fictício",
                        "body": "Este es un texto fictício",
                        "userId": 1}

nuevo_post = requests.post(f"{url}/posts", json=publicacion_ficticia)

#Mostra la resposta JSON.
print("Respuesta JSON:", nuevo_post.json())

#Mostra el codi d'estat.
print("Status_code post:", nuevo_post.status_code)

Respuesta JSON: {'title': 'Título fictício', 'body': 'Este es un texto fictício', 'userId': 1, 'id': 101}
Status_code post: 201

*5. Fes una petició PATCH per modificar parcialment una publicació existent.*

Mostra la resposta JSON.
Mostra el codi d'estat.

In [11]:
modificacion = {"title": "Título modificado parcialmente"}

response_patch = requests.patch(f"{url}/posts/1", json=modificacion)

#Mostra la resposta JSON.
print("Respuesta JSON:", response_patch.json())

#Mostra el codi d'estat.
print("Status_code modificación:", response_patch.status_code)

Respuesta JSON: {'userId': 1, 'id': 1, 'title': 'Título modificado parcialmente', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
Status_code modificación: 200

*6. Fes una petició DELETE sobre una publicació.*

Mostra la resposta JSON.
Mostra el codi d'estat.

In [12]:
response_delete = requests.delete(f"{url}/posts/1")

#Mostra la resposta JSON.
print("Respuesta JSON:", response_delete.json())

#Mostra el codi d'estat.
print("Status_code modificación:", response_delete.status_code)

Respuesta JSON: {}
Status_code modificación: 200

**Nivell 2**

Interacció amb una API pública real
*1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.*

In [ ]:
url = "https://open.er-api.com/v6/latest/USD"

*2. Llegeix la documentació de l'API:*

Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

Endpoints:
- Standard Requests: GET https://v6.exchangerate-api.com/v6/YOUR-API-KEY/latest/USD
- Pair Conversion Requests: GET https://v6.exchangerate-api.com/v6/YOUR-API-KEY/pair/EUR/GBP
- Historical Data Requests: GET https://v6.exchangerate-api.com/v6/YOUR-API-KEY/history/USD/YEAR/MONTH/DAY

Filtros:
Base currency (moneda base): /v6/latest/{BASE}
Data específica (histórico): /v6/{YYYY-MM-DD}
Cambio de moneda base en histórico: /v6/{YYYY-MM-DD}?base={BASE}
Ejemplo:
https://open.er-api.com/v6/2024-01-01?base=GBP

In [1]:
import requests

url = "https://open.er-api.com/v6/latest/USD"
response = requests.get(url)

try:
    data = response.json()
    print("Es JSON válido")
except:
    print("No es JSON")

Es JSON válido

*3. Fes una petició GET senzilla:*

Mostra el codi d'estat de la resposta.
Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [2]:
url = "https://open.er-api.com/v6/latest/EUR"

response = requests.get(url)

# 1. Mostrar el status_code
print("Status_code:", response.status_code)

# 2. Convertir a JSON
data = response.json()

# 3. Mostrar algunos campos
print("Resultado:", data["result"])
print("Base:", data["base_code"])
print("Data actualitzación:", data["time_last_update_utc"])
print("Tipo de cambio EUR a USD:", data["rates"]["USD"])

Status_code: 200
Resultado: success
Base: EUR
Data actualitzación: Mon, 16 Mar 2026 00:02:31 +0000
Tipo de cambio EUR a USD: 1.143327

*4. Converteix les dades a un DataFrame de pandas:*

Mostra les primeres files del DataFrame.

In [10]:
import pandas as pd

rates = data["rates"]

df = pd.DataFrame.from_dict(rates, orient="index", columns=["rate_vs_EUR"])
#crear toda la matriz de tipos de cambio
currencies = df.index
tipos_cambio = pd.DataFrame(index=currencies, columns=currencies)

for c1 in currencies:
    for c2 in currencies:
        tipos_cambio.loc[c1, c2] = rates[c2] / rates[c1]

#convertir a float
tipos_cambio = tipos_cambio.astype(float)

tipos_cambio.head()

,EUR,AED,AFN,ALL,AMD,ANG,AOA,ARS,AUD,AWG,...,XCD,XCG,XDR,XOF,XPF,YER,ZAR,ZMW,ZWG,ZWL
EUR,1.000000,4.198853,71.872601,96.091004,431.518004,2.046548,1062.780368,1660.390667,1.632936,2.046548,...,3.086972,2.046548,0.844876,655.957000,119.332000,272.911440,19.304448,22.382911,29.279200,29.279200
AED,0.238160,1.000000,17.117199,22.885060,102.770448,0.487406,253.112068,395.439104,0.388900,0.487406,...,0.735194,0.487406,0.201216,156.222902,28.420142,64.996665,4.597553,5.330720,6.973142,6.973142
AFN,0.013914,0.058421,1.000000,1.336963,6.003929,0.028475,14.787003,23.101859,0.022720,0.028475,...,0.042951,0.028475,0.011755,9.126663,1.660327,3.797155,0.268593,0.311425,0.407376,0.407376
ALL,0.010407,0.043697,0.747964,1.000000,4.490722,0.021298,11.060144,17.279356,0.016994,0.021298,...,0.032126,0.021298,0.008792,6.826414,1.241864,2.840135,0.200898,0.232935,0.304703,0.304703
AMD,0.002317,0.009730,0.166558,0.222681,1.000000,0.004743,2.462888,3.847790,0.003784,0.004743,...,0.007154,0.004743,0.001958,1.520115,0.276540,0.632445,0.044736,0.051870,0.067852,0.067852

**Nivell 3**

API d'Open Data Barcelona

*1. Utilitza l’API d’Open Data BCN per:*

Cercar un dataset del teu interès mitjançant package_search i package_show.

In [14]:
import requests

url_search = "https://opendata-ajuntament.barcelona.cat/data/api/action/package_search"

response = requests.get(url_search)
data = response.json()

print("Total encontrados:", data["result"]["count"])

for ds in data["result"]["results"]:
    print("-", ds["title"], "| ID:", ds["id"])

Total encontrados: 553
- Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council | ID: 331cba6c-7ca7-49d7-8ec7-19ff39d70aa3
- Receipts and quota of the register of the Vados Tax of the Barcelona City Council | ID: 7e63eeb0-670a-4bcc-bee9-1d89697a4501
- Receipts and charges from the motor vehicle tax roll of the Barcelona City Council | ID: e21b436f-7f84-4f7b-a3de-f7dc6b43264f
- Immigrants | ID: 778e5885-5bdb-416e-adbd-854632381ad1
- Emigrants | ID: 3d317361-0be9-4178-8566-4ff0b33d65a3
- Cancellations for undue inscription | ID: 6b03a0f0-3900-4fe4-ada8-c9428e4751ed
- Registrations by omission | ID: 36599a99-ca8f-4ae6-8531-7fae51123e88
- Deaths | ID: bd19689e-0ebe-4a4b-a11e-eb519bac3453
- Births | ID: dde567a3-0c39-4216-a6b7-8588fdf4ef07
- Population by geographical region of nationality and sex | ID: 28c20408-5bce-41db-9b83-1b85ac9b2548

In [16]:
url_show = "https://opendata-ajuntament.barcelona.cat/data/api/action/package_show"
params = {"id": "28c20408-5bce-41db-9b83-1b85ac9b2548"}

response = requests.get(url_show, params=params)
population = response.json()

#mostrar título y descripción
print("Título:", population["result"]["title"])
print("Descripción:", population["result"]["notes"])
population

Título: Population by geographical region of nationality and sex
Descripción: Population of Barcelona aggregated by geographical region of nationality and sex according to the Municipal Register of Inhabitants on January 1 of each year

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_show',
 'success': True,
 'result': {'notes_translated': {'ca': "Població de Barcelona agregada per la regió geogràfica associada a la nacionalitat i el sexe segons el registre del Padró Municipal d'Habitants a data 1 de gener de cada any",
   'en': 'Population of Barcelona aggregated by geographical region of nationality and sex according to the Municipal Register of Inhabitants on January 1 of each year',
   'es': 'Población de Barcelona agregada por región geográfica asociada a la nacionalidad y sexo según el registro del Padrón Municipal de Habitantes con fecha 1 de enero de cada año'},
  'geolocation': 'No',
  'code': 'pad_mdb_nacionalitat-regio_sexe',
  'url_tornada': {'ca': '', 'en': '', 'es': ''},
  'dataset_fields_description': 'Si la dada és menor que 5, s’indica com ‘’..’’',
  'fuente': "Ajuntament de Barcelona. Oficina Municipal de Dades (OMD). Padró Municipal d'Habitants",
  'private': False,
  'num_tags': 38,
  'api': 'Yes',
  'frequency': 'ANUAL',
  'id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
  'title_translated': {'ca': 'Població per regió geogràfica de nacionalitat i sexe',
   'en': 'Population by geographical region of nationality and sex',
   'es': 'Población por región geográfica de nacionalidad y sexo'},
  'metadata_modified': '2025-07-22T07:13:15.853137',
  'author': 'Gerència Municipal',
  'author_email': None,
  'isopen': True,
  'long_format': 'Yes',
  'state': 'active',
  'version': '',
  'mar_od': 'No',
  'relationships_as_object': [],
  'department': 'Oficina Municipal de Dades',
  'creator_user_id': '50d6b44b-a141-4dc6-b663-5deb4ab0dd63',
  'type': 'dataset',
  'resources': [{'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': True,
    'id': '3dce0dbd-5a7d-439a-b945-6bffc17a6c03',
    'size': '147685',
    'state': 'active',
    'api_access_number': 14,
    'api_access_number_absolute': 31,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 291,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2025_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-29T15:11:39.842927',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/3dce0dbd-5a7d-439a-b945-6bffc17a6c03/download',
    'downloads_absolute': 348,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.792903',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-30T02:10:53.332007',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 0,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '0dea1610-e615-4d81-9714-a374e1bb74c9',
    'size': '474533',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 105,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2025_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-29T15:10:20.024774',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/0dea1610-e615-4d81-9714-a374e1bb74c9/download',
    'downloads_absolute': 128,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.814288',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-30T02:10:53.355353',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 1,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '8caae93c-6196-490f-abd2-87eccda80776',
    'size': '146267',
    'state': 'active',
    'api_access_number': 1,
    'api_access_number_absolute': 1,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 93,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2024_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:17:19.851094',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/8caae93c-6196-490f-abd2-87eccda80776/download',
    'downloads_absolute': 106,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.836743',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.239828',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 2,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '08e3a0d7-7758-4d76-9e4b-89f2c2dc14c3',
    'size': '470187',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 44,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2024_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:15:57.855065',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/08e3a0d7-7758-4d76-9e4b-89f2c2dc14c3/download',
    'downloads_absolute': 58,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.856877',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.262492',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 3,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '7b7efabe-f08f-49e0-b1f9-eb116c6fdcc9',
    'size': '144228',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 48,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2023_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:14:35.491149',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/7b7efabe-f08f-49e0-b1f9-eb116c6fdcc9/download',
    'downloads_absolute': 54,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.876928',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.296396',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 4,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '026f6408-2fbe-404d-9620-6198bea2fd87',
    'size': '464252',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 28,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2023_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:13:13.699298',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/026f6408-2fbe-404d-9620-6198bea2fd87/download',
    'downloads_absolute': 32,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.908800',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.322010',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 5,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': 'a04fe536-d7ea-4fc5-95e5-ec029f58d265',
    'size': '143411',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 49,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2022_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:11:50.719551',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/a04fe536-d7ea-4fc5-95e5-ec029f58d265/download',
    'downloads_absolute': 55,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.927801',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.341514',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 6,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': 'ca281934-1f71-431c-a556-58382ca39be7',
    'size': '461353',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 25,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2022_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:10:28.721711',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/ca281934-1f71-431c-a556-58382ca39be7/download',
    'downloads_absolute': 29,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.950753',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.361323',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 7,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '8d695a37-9117-45de-af26-c58a91233421',
    'size': '143083',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 45,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2021_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:09:06.538321',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/8d695a37-9117-45de-af26-c58a91233421/download',
    'downloads_absolute': 50,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.969409',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.380763',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 8,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '65528d11-0a22-4f50-9b94-6f7f5e37ae65',
    'size': '460415',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 27,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2021_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:07:44.867534',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/65528d11-0a22-4f50-9b94-6f7f5e37ae65/download',
    'downloads_absolute': 31,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:51.989430',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.403562',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 9,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '3d849ad6-4208-4f90-b30c-8a1d7222dc30',
    'size': '142501',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 38,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2020_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:06:22.768197',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/3d849ad6-4208-4f90-b30c-8a1d7222dc30/download',
    'downloads_absolute': 40,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:52.010732',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.416970',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 10,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': 'fd0e65a4-c5d7-45fd-8117-bbbfefb92f33',
    'size': '458491',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 26,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2020_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:05:01.210643',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/fd0e65a4-c5d7-45fd-8117-bbbfefb92f33/download',
    'downloads_absolute': 29,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:52.031101',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.437439',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 11,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '94337cb7-3802-4eaf-87c4-be8c1d3c0fe4',
    'size': '141324',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 38,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2019_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:03:39.263480',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/94337cb7-3802-4eaf-87c4-be8c1d3c0fe4/download',
    'downloads_absolute': 42,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-03-16T02:11:52.051493',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.463042',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 12,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,

*2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.*

In [ ]:
resources = population["result"]["resources"]

datos_csv = [recurso for recurso in resources if recurso["format"].lower() in ["csv"]]

print("Recursos CSV encontrados:")
for recurso in datos_csv:
    print("-", recurso["name"], "| formato:", recurso["format"], "| URL:", recurso["url"])

Recursos CSV encontrados:
- 2025_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/3dce0dbd-5a7d-439a-b945-6bffc17a6c03/download
- 2024_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/8caae93c-6196-490f-abd2-87eccda80776/download
- 2023_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/7b7efabe-f08f-49e0-b1f9-eb116c6fdcc9/download
- 2022_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/a04fe536-d7ea-4fc5-95e5-ec029f58d265/download
- 2021_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/8d695a37-9117-45de-af26-c58a91233421/download
- 2020_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/3d849ad6-4208-4f90-b30c-8a1d7222dc30/download
- 2019_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/94337cb7-3802-4eaf-87c4-be8c1d3c0fe4/download
- 2018_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/9b5f8d9f-8c4a-4e71-8832-fb8119e070c9/download
- 2017_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/9fe403e0-c032-4a78-be0e-df0682973697/download
- 2016_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/08c60ad2-1731-428e-85cd-007b515e52ed/download
- 2015_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/d7833293-0872-4246-9403-112164015b60/download
- 2014_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/73240e48-6beb-4eb2-9140-4244fca7a13b/download
- 2013_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/2a95350b-e50a-46b8-b19e-b98c752ec876/download
- 2012_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/445295b5-aa53-4ddc-a358-8ebff35a4c46/download
- 2011_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/6d0b4651-bfaa-4705-84a5-45003a864f90/download
- 2010_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/9c15f8eb-baf7-4b58-93c7-ea0fcde2a3aa/download
- 2009_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/87a9468f-4ac5-488f-ae55-2865748fd1d3/download
- 2008_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/7b6a86a7-3923-498e-84b6-16fb6cb32ee9/download
- 2007_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/618348b8-dbda-48cf-a529-591e532f350e/download
- 2006_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/25c6c361-8a9e-4ad1-9c38-accae60ef423/download
- 2005_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/1e502d42-61bd-4e36-9cad-951de7688907/download
- 2004_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/6a941d9d-b699-4389-af02-fb12e0263e2c/download
- 2003_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/abd8ad76-acb9-469d-95c4-49a7faa0b0ad/download
- 2002_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/a4709ad1-904a-4376-a270-6b03642dcb89/download
- 2001_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/c9b5f39c-c67a-409a-9d4d-0ada11de127f/download
- 2000_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/87f1e2c0-d566-4697-90f9-e4f4552e4653/download
- 1999_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/064c2ac1-9101-4616-830c-646b904c84c3/download
- 1998_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/d54bd331-6c64-404f-8544-1109c653a881/download
- 1997_pad_mdb_nacionalitat-regio_sexe.csv | formato: CSV | URL: https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/50727070-da5b-4777-99c6-2e970a7e5250/download

In [ ]:
#url datos a utilizar:
url_recurso = datos_csv[0]["url"]

*3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:*

Recuperar almenys 100 registres.

In [21]:
recurso_id = datos_csv[0]["id"]
print(recurso_id)

3dce0dbd-5a7d-439a-b945-6bffc17a6c03

In [22]:
url_datastore = "https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search"

params = {"resource_id": recurso_id,
          "limit": 100}

response = requests.get(url_datastore, params=params)
datos_100 = response.json()

print("Registros recuperados:", len(datos_100["result"]["records"]))

Registros recuperados: 100

*4. Converteix els resultats a un DataFrame.*

In [23]:
import pandas as pd

datos_nacionalidad_100 = pd.DataFrame(datos_100["result"]["records"])
datos_nacionalidad_100.head()

,NACIONALITAT_REGIO,Codi_Districte,SEXE,Nom_Districte,Codi_Barri,Nom_Barri,Valor,Data_Referencia,_id
0,1,1,1,Ciutat Vella,1,el Raval,20,2025-01-01T00:00:00,1
1,1,1,2,Ciutat Vella,1,el Raval,31,2025-01-01T00:00:00,2
2,2,1,1,Ciutat Vella,1,el Raval,12,2025-01-01T00:00:00,3
3,2,1,2,Ciutat Vella,1,el Raval,15,2025-01-01T00:00:00,4
4,3,1,1,Ciutat Vella,1,el Raval,695,2025-01-01T00:00:00,5

*5. Desa el DataFrame en un fitxer .csv.*

In [25]:
datos_nacionalidad_100.to_csv("datos_nacionalidad_100.csv", index=False, encoding='utf-8')
print("csv guardado con éxito.")

csv guardado con éxito.